controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
  - name: left_arm_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_gripper_base_gripper_left_joint
      - left_gripper_base_gripper_right_joint
  - name: right_arm_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_gripper_base_gripper_left_joint
      - right_gripper_base_gripper_right_joint
  - name: Kinect2_Target_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - neck_shoulder_pan_joint
      - neck_shoulder_lift_joint
      - neck_elbow_joint
      - neck_wrist_1_joint
      - neck_wrist_2_joint
      - neck_wrist_3_joint
      - neck_joint_end
      - head1
      - head2
      - head3
  - name: kinect_target_actuator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - head3
  - name: neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - neck_shoulder_pan_joint
      - neck_shoulder_lift_joint
      - neck_elbow_joint
      - neck_wrist_1_joint
      - neck_wrist_2_joint
      - neck_wrist_3_joint
  - name: Kinect2_sensor_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      []
