# joint_limits.yaml only required if your robot uses non-standard joint names
# She order of this list should match that expected by your robot's socket interface. 
# Typically Base -> Tip.
controller_joint_names: [neck_shoulder_pan_joint, neck_shoulder_lift_joint, neck_elbow_joint, neck_wrist_1_joint, neck_wrist_2_joint, neck_wrist_3_joint, neck_joint_end, head1, head2, head3]
